### ISSUE TITLE
Crash when searching "an" in the creative menu

### ISSUE THREAD

**Issue by Midnight145** [jss2a98aj/NotFine#48] opened 2024-12-02 23:47 UTC
Seemingly crashes when it tries to render the anvil texture in the search results.

Unimixins 0.1.19
NotFine 0.2.5
No other mods

[crash-2024-12-02_17.45.47-client.txt](https://github.com/user-attachments/files/17985110/crash-2024-12-02_17.45.47-client.txt)

**Comment by Midnight145** [comment] 2024-12-02 23:50
ah, looks like duplicate of #36, feel free to close

**Comment by unicornbloods** [comment] 2024-12-02 23:50
Duplicate of [36](https://github.com/jss2a98aj/NotFine/issues/36)

**Closed** 2024-12-03 00:21 UTC
